services:
  - type: web
    name: seo-pdf-generator
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PORT
        value: 8000
    autoDeploy: true
