services:
  - type: web
    name: seo-pdf-renderer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
